apiVersion: apps/v1
kind: Deployment
metadata:
  name: auto-scaler
  namespace: app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: auto-scaler
  template:
    metadata:
      labels:
        app: auto-scaler
      annotations:
        sidecar.istio.io/inject: "false"
    spec:
      containers:
      - name: auto-scaler
        image: localhost:32000/auto-scaler
        resources:
          requests:
            cpu: "500m"
            memory: "1Gi"
          limits:
            memory: "1Gi"
        ports:
        - containerPort: 50051
---
apiVersion: v1
kind: Service
metadata:
  name: auto-scaler
  namespace: app
spec:
  ports:
  - port: 50051
    targetPort: 50051
  selector:
    app: auto-scaler
  
---
apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: bi-scaler
  namespace: app
spec:
  scaleTargetRef:
    name: productpage-v1        
  cooldownPeriod: 3     
  minReplicaCount: 1            
  maxReplicaCount: 10           
  triggers:
  - type: external-push         
    metadata:
      scalerAddress: auto-scaler.app:50051
  advanced:
    horizontalPodAutoscalerConfig:
      behavior:
        scaleUp:
          stabilizationWindowSeconds: 1
          policies:
          - type: Percent
            value: 100                 
            periodSeconds: 5       
          - type: Pods
            value: 4
            periodSeconds: 5

        scaleDown:
          stabilizationWindowSeconds: 1
          policies:
          - type: Percent
            value: 100                 
            periodSeconds: 5     
          - type: Pods
            value: 4
            periodSeconds: 5
