{
 "title": "KEDA",
 "description": "Visualize metrics provided by KEDA",
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   {
    "name": "namespace",
    "query": {
     "query": "label_values(keda_scaler_active,exported_namespace)"
    }
   },
   {
    "name": "scaledObject",
    "query": {
     "query": "label_values(keda_scaler_active{exported_namespace=\"$namespace\"},scaledObject)"
    }
   },
   {
    "name": "scaler",
    "query": {
     "query": "label_values(keda_scaler_active{exported_namespace=\"$namespace\"},scaler)"
    }
   },
   {
    "name": "metric",
    "query": {
     "query": "label_values(keda_scaler_active{exported_namespace=\"$namespace\"},metric)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Metric Server", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Scaler Total Errors",
   "type": "timeseries",
   "description": "The total number of errors encountered for all scalers.",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "Errors/sec" } },
   "targets": [
    {
     "expr": "sum by(job) (rate(keda_scaler_detail_errors_total{}[5m]))",
     "legendFormat": "{{ job }}"
    }
   ]
  },
  {
   "title": "Scaler Errors",
   "type": "timeseries",
   "description": "The number of errors that have occurred for each scaler.",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "Errors/sec" } },
   "targets": [
    {
     "expr": "sum by(scaler) (rate(keda_scaler_detail_errors_total{exported_namespace=~\"$namespace\", scaledObject=~\"$scaledObject\", scaler=~\"$scaler\"}[5m]))",
     "legendFormat": "{{ scaler }}"
    }
   ]
  },
  {
   "title": "Scaled Object Errors",
   "type": "timeseries",
   "description": "The number of errors that have occurred for each scaled object.",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "Errors/sec" } },
   "targets": [
    {
     "expr": "sum by(scaledObject) (rate(keda_scaled_object_errors_total{exported_namespace=~\"$namespace\", scaledObject=~\"$scaledObject\"}[5m]))",
     "legendFormat": "{{ scaledObject }}"
    }
   ]
  },
  { "title": "Scale Target", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 10 } },
  {
   "title": "Scaler Metric Value",
   "type": "timeseries",
   "description": "The current value for each scaler’s metric that would be used by the HPA in computing the target average.",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum by(metric) (keda_scaler_metrics_value{exported_namespace=~\"$namespace\", metric=~\"$metric\", scaledObject=\"$scaledObject\"})",
     "legendFormat": "{{ metric }}"
    }
   ]
  },
  {
   "title": "Current/max replicas (time based)",
   "type": "timeseries",
   "description": "shows current replicas against max ones based on time difference",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "kube_horizontalpodautoscaler_status_current_replicas{namespace=\"$namespace\",horizontalpodautoscaler=\"keda-hpa-$scaledObject\"}",
     "legendFormat": "current_replicas"
    },
    {
     "expr": "kube_horizontalpodautoscaler_spec_max_replicas{namespace=\"$namespace\",horizontalpodautoscaler=\"keda-hpa-$scaledObject\"}",
     "legendFormat": "max_replicas"
    }
   ]
  },
  {
   "title": "Changes in replicas",
   "type": "state-timeline",
   "description": "shows current replicas against max ones based on time difference",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "delta(kube_horizontalpodautoscaler_status_current_replicas{namespace=\"$namespace\",horizontalpodautoscaler=\"keda-hpa-$scaledObject\"}[1m])",
     "legendFormat": "."
    }
   ]
  },
  {
   "title": "Current/max replicas",
   "type": "gauge",
   "description": "shows current replicas against max ones",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 36 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "kube_horizontalpodautoscaler_status_current_replicas{namespace=\"$namespace\",horizontalpodautoscaler=\"keda-hpa-$scaledObject\"}",
     "legendFormat": "current_replicas"
    },
    {
     "expr": "kube_horizontalpodautoscaler_spec_max_replicas{namespace=\"$namespace\",horizontalpodautoscaler=\"keda-hpa-$scaledObject\"}",
     "legendFormat": "max_replicas"
    }
   ]
  }
 ]
}