// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package prometheus

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// PrometheusServiceClient is the client API for PrometheusService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type PrometheusServiceClient interface {
	GetPrometheusData(ctx context.Context, in *PrometheusRequest, opts ...grpc.CallOption) (*PrometheusResponse, error)
}

type prometheusServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewPrometheusServiceClient(cc grpc.ClientConnInterface) PrometheusServiceClient {
	return &prometheusServiceClient{cc}
}

func (c *prometheusServiceClient) GetPrometheusData(ctx context.Context, in *PrometheusRequest, opts ...grpc.CallOption) (*PrometheusResponse, error) {
	out := new(PrometheusResponse)
	err := c.cc.Invoke(ctx, "/prometheus.PrometheusService/GetPrometheusData", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// PrometheusServiceServer is the server API for PrometheusService service.
// All implementations must embed UnimplementedPrometheusServiceServer
// for forward compatibility
type PrometheusServiceServer interface {
	GetPrometheusData(context.Context, *PrometheusRequest) (*PrometheusResponse, error)
	mustEmbedUnimplementedPrometheusServiceServer()
}

// UnimplementedPrometheusServiceServer must be embedded to have forward compatible implementations.
type UnimplementedPrometheusServiceServer struct {
}

func (UnimplementedPrometheusServiceServer) GetPrometheusData(context.Context, *PrometheusRequest) (*PrometheusResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetPrometheusData not implemented")
}
func (UnimplementedPrometheusServiceServer) mustEmbedUnimplementedPrometheusServiceServer() {}

// UnsafePrometheusServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to PrometheusServiceServer will
// result in compilation errors.
type UnsafePrometheusServiceServer interface {
	mustEmbedUnimplementedPrometheusServiceServer()
}

func RegisterPrometheusServiceServer(s grpc.ServiceRegistrar, srv PrometheusServiceServer) {
	s.RegisterService(&PrometheusService_ServiceDesc, srv)
}

func _PrometheusService_GetPrometheusData_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PrometheusRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PrometheusServiceServer).GetPrometheusData(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/prometheus.PrometheusService/GetPrometheusData",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PrometheusServiceServer).GetPrometheusData(ctx, req.(*PrometheusRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// PrometheusService_ServiceDesc is the grpc.ServiceDesc for PrometheusService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var PrometheusService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "prometheus.PrometheusService",
	HandlerType: (*PrometheusServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetPrometheusData",
			Handler:    _PrometheusService_GetPrometheusData_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "prom.proto",
}
