# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: prom.proto
# Protobuf Python Version: 5.27.2
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    27,
    2,
    '',
    'prom.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\nprom.proto\x12\nprometheus\"\"\n\x11PrometheusRequest\x12\r\n\x05query\x18\x01 \x01(\t\"\"\n\x12PrometheusResponse\x12\x0c\n\x04\x64\x61ta\x18\x01 \x01(\t2g\n\x11PrometheusService\x12R\n\x11GetPrometheusData\x12\x1d.prometheus.PrometheusRequest\x1a\x1e.prometheus.PrometheusResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'prom_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_PROMETHEUSREQUEST']._serialized_start=26
  _globals['_PROMETHEUSREQUEST']._serialized_end=60
  _globals['_PROMETHEUSRESPONSE']._serialized_start=62
  _globals['_PROMETHEUSRESPONSE']._serialized_end=96
  _globals['_PROMETHEUSSERVICE']._serialized_start=98
  _globals['_PROMETHEUSSERVICE']._serialized_end=201
# @@protoc_insertion_point(module_scope)
